Add fallback commands for the case where the IPFS daemon isn't running
keorn/clj-ipfs-api pull request #8
Opened 2019-03-08 12:37 UTC by DCPRevere

When the IPFS daemon isn't running and this library is loaded, the library will have no functions. This causes errors when symbols cannot be found, and is a pain for everything from development to CI.

To get around this I have added a list of functions from `ipfs commands` that will be loaded in the case that the IPFS daemon isn't running, but change nothing if it is.

2019-03-08 12:56 UTC, keorn requested changes
Thanks a lot for the contribution!

The only issues I see are all the unnecessary extra lines and exposing functions that should not be exposed. It would be great if this PR would only introduce the change in the title.

2019-03-08 12:56 UTC, keorn commented on src/clj_ipfs_api/core.clj
> -(defn- empty-fn
Why expose this function?

2019-03-08 12:56 UTC, keorn commented on src/clj_ipfs_api/core.clj
> -(defn- unpack-cmds
Why expose this function?

2019-03-08 12:56 UTC, keorn commented on src/clj_ipfs_api/core.clj
> -(defn- setup!
Why expose this function?

2019-03-08 12:56 UTC, keorn commented on src/clj_ipfs_api/core.clj
> -(defn- api-request
Why expose this function?

2019-03-08 12:56 UTC, keorn commented on src/clj_ipfs_api/core.clj
> -(defn- assemble-query
Why expose this function?

2019-03-08 15:24 UTC, DCPRevere commented on src/clj_ipfs_api/core.clj
> -(defn- setup!
It allows one to call `setup` again once the daemon is running?

2019-03-08 15:25 UTC, DCPRevere commented
The changes from `defn-` to `defn` are just my personal preference, but as you're the owner I'll reverse these changes.

2019-03-08 15:29 UTC, DCPRevere commented on src/clj_ipfs_api/core.clj
> -(defn- setup!
You already expose `set-api-url!` which calls `setup!` again.

2019-03-10 08:15 UTC, keorn requested changes
Ok, I think `defn-` issue is pretty clear. I do not want random names to be taken by internal lib functions when importing the namespace.

As for the blank lines, I am fine with a single blank line, but not multiple between `defn`s. Currently the definitions are grouped based on ones belonging logically together.

Anyway, if you want any changes besides the title of the PR then please make another PR that explicitly targets those, such as any formatting changes.

2019-03-10 08:15 UTC, keorn commented on src/clj_ipfs_api/commands.clj
> +  (map #(clojure.string/split % #" ") cmds))
Is it here because above is the default node output and you want to make updating these easier? If so, then please comment.

However this is not the nicest, if you bundle something in then better pre-process it and not make everyone do it on startup.

2019-05-01 09:02 UTC, DCPRevere commented on src/clj_ipfs_api/commands.clj
> +  (map #(clojure.string/split % #" ") cmds))
Done.

2019-07-01 08:16 UTC, keorn approved these changes

2019-07-01 08:16 UTC, merged

2019-07-01 08:17 UTC, keorn commented
Sorry for delay, thanks for contribution!